## Configuracion de Spring
spring:
  application:
    name: ms-productos
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tienda}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

## Configuracion de Instancia
server:
  port: 8089

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-productos

